- hosts: '{{ target }}'

  tasks:
   - name: Solve broken yum update
     shell: yum erase -y qpid-cpp-client

   - name: Remove RHEL repositories
     shell: rm -Rf /etc/yum.repos.d/*

   - name: Disable RHEL repositories
     shell: yum-config-manager --disable redhat.repo rhel-source.repo centos.repo

  - name: Create CentOS Repository Online
    copy: src=/etc/ansible/playbooks/repo-online/epel.repo dest=/etc/yum.repos.d/epel.repo

   - name: Yum clean database
     shell: yum clean all

   - name: Yum Enable epel repository
     shell: yum-config-manager --enable epel.repo
